### ISSUE TITLE
Upgrade Postgres requirement to 14.7 or newer

### ISSUE THREAD

**Issue by duncand** [bcgov/cirmo-dpia#1012]
The DPIA backend DBMS specified in the Docker config is currently Postgres version 10.21 but it should be something modern like 15.2 or 14.7 instead.

(Likewise for every other bcgov project still specifying a Postgres version older than 14.7 or so.)

One key reason for this is that Postgres 10 is no longer supported by its creators and so depending on it presents a security risk.

Another key reason is that Postgres 10 is 5 major versions behind the latest production version and so we are missing out on using 5 years' worth of very useful new features and improvements.

(It is also notable that Postgres 10 was already 4 major versions out of date, and half a year from end of support, when the earliest surviving commit of 2022 Jun 17 was made to the DPIA repository.)

The DPIA Docker config specifies that the `dpia-db` image is `postgres:10.21-alpine3.16`.

See the Docker site for the newer options:

<https://hub.docker.com/_/postgres>

The most minimal update that is still supported by upstream is `11.19-alpine3.17`.

The newest update is `15.2-alpine3.17` to get a major version that is a few months old.

If you want to be a bit more conservative, the second to newest major version is `14.7-alpine3.17` and that is the oldest I would recommend.

Postgres is very good at keeping high quality and reliability, so one shouldn't really see any need to be more than a year or so out of date to feel that they are using something stable and bug free.

Since Postgres is very good with backwards-compatibility for minor versions of the same major, specifying an alternate alias like `15-alpine` or `14-alpine` means that any given time you get the latest minor version for the major without having to specify it explicitly, meaning less maintenance.

Note that Postgres major version updates mean a different on disk format for data directories, so this change is only a drop-in replacement in scenarios where upgrading users would create a database from scratch, like new users, or a dump/restore or replication migration will be needed.

**Comment by akroon3r** [comment]
Hey Darren,

I appreciate the feedback. Currently this project is going to be transitioning to a CrunchyDB instance in Openshift in the next month, as I'm currently working on some higher prioritized issues in our DevOps backlog.

**Comment by duncand** [comment]
Thank you Adam.  Given that you have an imminent alternate solution, I will close this issue.
